version: '3.7'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: myapp-server
    container_name: server
    command: /usr/src/app/node_modules/.bin/nodemon server.js
    volumes:
      - ./server/:/usr/src/app:cached
      - /usr/src/app/node_modules
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    env_file: ./server/.env
    environment:
      CHOKIDAR_USEPOLLING: "true"
    networks:
      - app-network
  mongo:
    image: mongo
    volumes:
      - data-volume:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network

  react-ui:
    build:
      context: ./client
    image: myapp-client
    container_name: react-ui
    command: npm start
    volumes:
      - ./client:/usr/src/app/my-app
      - /usr/src/app/my-app/node_modules
    stdin_open: true
    depends_on:
      - server
    ports:
      - "3000:3000"
    environment:
      CHOKIDAR_USEPOLLING: "true"
    networks:
      - app-network

networks:
    app-network:
        driver: bridge

volumes:
    data-volume:
    node_modules:
    web-root:
      driver: local
